### ISSUE TITLE
Is there a good reason that the envopt fixture is scoped to function?

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/ci_watson#33]
I think `envopt` fixture should be scoped to `"session"`, as it is set at the session level.

This is important if one wants to use `envopt` in a fixture that is scoped to class, module or session.  Currently it cannot be used, as a fixture with `scope="function"` can't be used in a fixture with `scope="module"` or higher.

Example error message when one tries to do this:
```
_________________ ERROR at setup of test_miri_image2pipeline[cal] __________________
ScopeMismatch: You tried to access the 'function' scoped fixture 'envopt' with a 'module' scoped request object, involved factories
jwst/tests/test_miri_image2pipeline.py:11:  def run_pipeline(envopt, jail)
../../miniconda3/envs/jwst/lib/python3.7/site-packages/ci_watson/plugin.py:80:  def envopt(request)
```

**Comment by pllim** [comment]
Feel free to change it, as long as what you change is backward compatible.

**Comment by jdavies-st** [comment]
I feel like it should be, as it's basically impossible to change `envopt` during a session.  I.e. it gets set once on invocation of pytest:
```
pytest --env=dev
```
So almost by definition it is set at the session level, but every time the fixture is then passed to a test function it grabs the same value for every test, for as many tests as you have.  Better to grab it once and hang on to it.
