### ISSUE TITLE
Warning on timeout is issued no matter what

### ISSUE THREAD

**Issue by pllim** [spacetelescope/ci_watson#54]
https://github.com/spacetelescope/ci_watson/blob/57df82132b3977decae820187d3e53d5323225b8/ci_watson/hst_helpers.py#L121

```
UserWarning: Deprecation Warning: `timeout` parameter no longer needed.
```

The above warning is issued even if the function is called without providing a `timeout` keyword. Also it is not the correct warning category.

**Comment by stscirij** [comment]
Will this parameter be removed from the interface of download_crds() and the warning removed?

**Comment by pllim** [comment]
@stscirij , I went ahead and removed it in #58
