### ISSUE TITLE
Add Zenodo badge after the next GitHub Release

### ISSUE THREAD

**Issue by pllim** [spacetelescope/ci_watson#62]
I toggled the Zenodo webhook on but you won't get DOI until a GitHub Release is made.

**Comment by zacharyburnett** [comment]
you can also add a `CITATION.cff` to make citing super easy (see https://github.com/spacetelescope/jwst/blob/master/CITATION.cff)

**Comment by pllim** [comment]
Feel free to add it if you want.

**Comment by pllim** [comment]
Done in 7ff8a10 . If you really want CFF, please open new issue or PR. This issue is only about Zenodo. Thanks.
