### ISSUE TITLE
Automate release and update wiki

### ISSUE THREAD

**Issue by pllim** [spacetelescope/ci_watson#65]
@braingram , there hasn't been a release for months. Maybe you can add a workflow to automate the release, update https://github.com/spacetelescope/ci_watson/wiki , and make a new release? Thanks!

**Comment by pllim** [comment]
Though I am not sure if there are any user facing changes since https://github.com/spacetelescope/ci_watson/releases/tag/0.6.2 . If not, then maybe not urgent. 🤷‍♀️

**Comment by braingram** [comment]
@zacharyburnett is there a common release workflow you'd like to reuse for this repo?

**Comment by zacharyburnett** [comment]
yes indeed, we can basically copy-paste the `build` workflow from https://github.com/spacetelescope/stpipe/blob/main/.github/workflows/build.yml, and it should function identically

**Comment by braingram** [comment]
For updating the wiki I don't have the required permissions. Perhaps adding:
```
This follows the same process as: https://github.com/spacetelescope/stpipe/wiki/Release-Process
```
Would suffice?

Given my lack of permissions I expect I cannot complete the steps required for a release. @zacharyburnett would you or @jhunkeler make a release for this package? As mentioned above it's not urgent.

**Comment by pllim** [comment]
Please don't forget to check the hstcal and acstools test suites too with your Path stuff. Thanks!

**Comment by pllim** [comment]
I updated the wiki.
