### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/ci_watson#7]
Follow up of #3. Do we need a release? If so, `astroconda`, or PyPI, or both?

**Comment by jhunkeler** [comment]
I'm inclined to leave this as a git submodule and bundle it via `MANIFEST.in`. I've had bad experiences in the past with `astropy-helpers` getting installed (accidentally or on purpose) into `site-packages` and  their little bootstrap script choosing the wrong version.

What are your thoughts? This package _probably_ won't be useful to anyone outside of STScI.

**Comment by pllim** [comment]
I also have bad experiences with `submodule` in a package, which depends on another package, which also has the same `submodule` but pinned at a different point of history...

Submodule or external dependency both have their own pros and cons. I would have to defer to the infrastructure experts that are you (@jhunkeler ) and @rendinam .

Yes, won't be useful to people outside of STScI. But might be useful across divisions.

**Comment by jhunkeler** [comment]
Good point. `ci-watson`'s dependencies cannot be resolved unless it gets installed, or the package using it provides those dependencies in their `setup.py`.

This alone might be enough incentive to make it a standalone package (released on pypi, etc, etc). Now I have to ask... is there a point to implementing it as a submodule if the dependencies might not be resolved at build/run-time?

**Comment by pllim** [comment]
`pytest` is the only hard dependency of `ci-watson` after #3 is merged. I mean, `astropy` is still used in a function but it won't throw `ImportError` until that function is run, hence making `astropy` is an optional dependency. However, not all packages have `pytest` as a dependency. But... if they use `astropy`, `pytest` would be installed anyway... 🤷‍♀️

**Comment by pllim** [comment]
Done in https://github.com/spacetelescope/ci_watson/releases/tag/0.1 and astroconda/astroconda-contrib#399
